export interface StudentWorkAsset {
  type: "image" | "video" | "youtube" | "sketchfab";
  src: string;
  lossless?: boolean;
  width?: number;
  height?: number;
  poster?: string;
  caption?: string;
}

/**
 * One selected piece of student work.
 *
 * Fill these when adding a piece:
 *   title, student, course, year, description, software,
 *   cover (path under /images/student-work/<slug>/), assets
 *
 * Do not invent entries. Wait for the specific pieces.
 */
export interface StudentWorkProject {
  slug: string;
  title: string;
  student?: string;
  course?: string;
  year?: string;
  description: string;
  software: string[];
  cover: string;
  coverAspect: number;
  coverPosition?: string;
  assets: StudentWorkAsset[];
}

export const studentProjects: StudentWorkProject[] = [
  {
    slug: "ataxia",
    title: "Ataxia",
    student: "Team Ataxia",
    description: "",
    software: [],
    cover: "/images/student-work/ataxia/cover.webp",
    coverAspect: 1.7778,
    assets: [
      {
        type: "video",
        src: "/videos/student-work/ataxia-trailer.mp4",
        poster: "/images/student-work/ataxia/cover.webp",
        width: 1280,
        height: 720,
        caption: "Trailer",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/poster.webp",
        width: 1733,
        height: 2400,
        caption: "Poster",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-01.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 1",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-02.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 2",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-03.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 3",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-04.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 4",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-05.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 5",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-06.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 6",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-07.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 7",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-08.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 8",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-09.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 9",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-10.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 10",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/screenshot-11.webp",
        width: 950,
        height: 488,
        caption: "Gameplay 11",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-apartment.webp",
        width: 576,
        height: 792,
        caption: "Apartment presentation sheet",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-barbershop.webp",
        width: 576,
        height: 792,
        caption: "Barbershop presentation sheet",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-fat-kid.webp",
        width: 576,
        height: 792,
        caption: "Fat Kid presentation sheet",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-oldsmobile.webp",
        width: 576,
        height: 792,
        caption: "Oldsmobile presentation sheet",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-police-car.webp",
        width: 576,
        height: 792,
        caption: "Police car presentation sheet",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-theater.webp",
        width: 1925,
        height: 2560,
        caption: "The Sunnyside Cinema. Asset by Erika Hollice",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-adam-seil-diner.webp",
        width: 1280,
        height: 1452,
        caption: "Adam Seil. Diner",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-edwin-reyes.webp",
        width: 1978,
        height: 2560,
        caption: "Edwin Reyes. Medium house",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-kent-lam-chevy.webp",
        width: 576,
        height: 792,
        caption: "Kent Lam. Chevy",
      },
      {
        type: "image",
        src: "/images/student-work/ataxia/sheet-osvil-cisneros.webp",
        width: 1978,
        height: 2560,
        caption: "Osvil Cisneros. Fish Lipz",
      },
    ],
  },
  {
    slug: "rock",
    title: "Rock",
    course: "Digital Sculpting",
    description: "",
    software: [],
    cover: "/images/student-work/rock/cover.webp",
    coverAspect: 1.5459,
    assets: [
      {
        type: "image",
        src: "/images/student-work/rock/cover.webp",
        width: 2560,
        height: 1656,
        caption: "Natalie LeComte. Scoria",
      },
      {
        type: "image",
        src: "/images/student-work/rock/andrew-barrett.webp",
        width: 1920,
        height: 1080,
        caption: "Andrew Barrett. Lapis lazuli",
      },
      {
        type: "image",
        src: "/images/student-work/rock/ava-hermann.webp",
        width: 1920,
        height: 1294,
        caption: "Ava Hermann",
      },
      {
        type: "image",
        src: "/images/student-work/rock/brennan-doyle.webp",
        width: 1920,
        height: 1080,
        caption: "Brennan Doyle",
      },
      {
        type: "image",
        src: "/images/student-work/rock/cameron-dava.webp",
        width: 1920,
        height: 1080,
        caption: "Cameron Dava",
      },
      {
        type: "image",
        src: "/images/student-work/rock/elle-li.webp",
        width: 2100,
        height: 1500,
        caption: "Elle Li",
      },
      {
        type: "image",
        src: "/images/student-work/rock/lauren-mckenzie.webp",
        width: 1224,
        height: 792,
        caption: "Lauren McKenzie. Ammonites",
      },
      {
        type: "image",
        src: "/images/student-work/rock/emily-waugh.webp",
        width: 1920,
        height: 1080,
        caption: "Emily Waugh. Bismuth",
      },
      {
        type: "image",
        src: "/images/student-work/rock/cameron-cooper.webp",
        width: 2560,
        height: 1978,
        caption: "Cameron Cooper. Raw amethyst",
      },
      {
        type: "image",
        src: "/images/student-work/rock/stibnite.webp",
        width: 1920,
        height: 1080,
        caption: "Stibnite study",
      },
      {
        type: "image",
        src: "/images/student-work/rock/sierra-bailey-van-kuren.webp",
        width: 1440,
        height: 1080,
        caption: "Sierra Bailey-Van Kuren. Turquoise",
      },
    ],
  },
  {
    slug: "animal-sculpts",
    title: "Animal Sculpts",
    course: "Digital Sculpting",
    description: "",
    software: [],
    cover: "/images/student-work/animal-sculpts/cover.webp",
    coverAspect: 1.0196,
    assets: [
      {
        type: "image",
        src: "/images/student-work/animal-sculpts/ava-hermann.webp",
        width: 1920,
        height: 1883,
        caption: "Ava Hermann. Baby black rhino",
      },
      {
        type: "image",
        src: "/images/student-work/animal-sculpts/llama.webp",
        width: 1535,
        height: 834,
        caption: "Llama",
      },
      {
        type: "image",
        src: "/images/student-work/animal-sculpts/llama-clay.webp",
        width: 1535,
        height: 834,
        caption: "Llama. Clay render",
      },
      {
        type: "image",
        src: "/images/student-work/animal-sculpts/llama-head-clay.webp",
        width: 1535,
        height: 834,
        caption: "Llama. Head, clay render",
      },
      {
        type: "image",
        src: "/images/student-work/animal-sculpts/charles-mcmahan.webp",
        width: 1280,
        height: 720,
        caption: "Charles McMahan. Hybrid rhino",
      },
      {
        type: "image",
        src: "/images/student-work/animal-sculpts/noah-davis.webp",
        width: 1920,
        height: 1080,
        caption: "Noah Davis. Alligator snapping turtle",
      },
    ],
  },
  {
    slug: "characters",
    title: "Characters",
    course: "Characters",
    description: "",
    software: [],
    cover: "/images/student-work/characters/cover.webp",
    coverAspect: 0.9834,
    assets: [
      {
        type: "image",
        src: "/images/student-work/characters/lauren-mckenzie.webp",
        width: 1243,
        height: 1264,
        caption: "Lauren McKenzie",
      },
      {
        type: "image",
        src: "/images/student-work/characters/lauren-mckenzie-variations.webp",
        width: 1920,
        height: 1118,
        caption: "Lauren McKenzie. Texture variations",
      },
      {
        type: "image",
        src: "/images/student-work/characters/christian-turner.webp",
        width: 1474,
        height: 1106,
        caption: "Christian Turner. Angel soldier",
      },
      {
        type: "image",
        src: "/images/student-work/characters/christian-turner-variants.webp",
        width: 1284,
        height: 893,
        caption: "Christian Turner. Color variants",
      },
      {
        type: "image",
        src: "/images/student-work/characters/christian-turner-retopo.webp",
        width: 1920,
        height: 1080,
        caption: "Christian Turner. Retopo",
      },
    ],
  },
  {
    slug: "props-environment",
    title: "Props and Environment",
    description: "",
    software: [],
    cover: "/images/student-work/props-environment/cover.webp",
    coverAspect: 1.3333,
    assets: [
      {
        type: "image",
        src: "/images/student-work/props-environment/jesse-walsh.webp",
        width: 1024,
        height: 768,
        caption: "Jesse Walsh. Bohemian Bridge",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/number-10-saloon.webp",
        width: 1656,
        height: 2560,
        caption: "Number 10 Saloon",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/number-10-saloon-render.webp",
        width: 2560,
        height: 2560,
        caption: "Number 10 Saloon. Render",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/number-10-saloon-sign.webp",
        width: 1280,
        height: 1024,
        caption: "Number 10 Saloon. Sign",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/eddy-einikis.webp",
        width: 2560,
        height: 1545,
        caption: "Eddy Einikis. Wooden bridge",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/vanessa-grass.webp",
        width: 2560,
        height: 2295,
        caption: "Vanessa Grass. Windmill",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/josh-huseman.webp",
        width: 1961,
        height: 1471,
        caption: "Josh Huseman. Sewer interior",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/chris-ozouf.webp",
        width: 1280,
        height: 720,
        caption: "Chris Ozouf. Door",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/industrial-door.webp",
        width: 1280,
        height: 720,
        caption: "Industrial door",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/larry-griffin.webp",
        width: 1024,
        height: 1296,
        caption: "Larry Griffin. Archway",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/larry-griffin-render.webp",
        width: 1024,
        height: 1024,
        caption: "Larry Griffin. Archway render",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/column.webp",
        width: 350,
        height: 524,
        caption: "Column",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/hazard-crate.webp",
        width: 1656,
        height: 2560,
        caption: "Hazard crate",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/hazard-crate-render.webp",
        width: 640,
        height: 480,
        caption: "Hazard crate. Render",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/jesse-walsh-dumpster.webp",
        width: 1024,
        height: 768,
        caption: "Jesse Walsh. Dumpster",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/broken-crates.webp",
        width: 1280,
        height: 720,
        caption: "Broken crates",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/jeremy-mack.webp",
        width: 1656,
        height: 2560,
        caption: "Jeremy Mack. Arca crate",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/andrew-barrett-gazebo.webp",
        width: 1920,
        height: 1079,
        caption: "Andrew Barrett. Gazebo",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/cassidy-rayfield-gazebo.webp",
        width: 1920,
        height: 1080,
        caption: "Cassidy Rayfield. Gazebo",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/osvil-cisneros-barrels.webp",
        width: 2048,
        height: 2560,
        caption: "Osvil Cisneros. Barrels",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/cameron-cooper-barricade.webp",
        width: 576,
        height: 792,
        caption: "Cameron Cooper. Barricade",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lauren-smith.webp",
        width: 1920,
        height: 1080,
        caption: "Lauren Smith. Morse tapper",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lauren-smith-detail.webp",
        width: 1920,
        height: 1080,
        caption: "Lauren Smith. Morse tapper, detail",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lauren-smith-morse-sheet.webp",
        width: 1920,
        height: 1080,
        caption: "Lauren Smith. Morse tapper, presentation",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lauren-smith-morse-clay.webp",
        width: 1920,
        height: 1080,
        caption: "Lauren Smith. Morse tapper, clay",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lauren-smith-shelf.webp",
        width: 1920,
        height: 1080,
        caption: "Lauren Smith. Library shelf",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lauren-smith-tesla.webp",
        width: 1920,
        height: 1080,
        caption: "Lauren Smith. Tesla coil",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/lindsey-kurkiewicz.webp",
        width: 921,
        height: 915,
        caption: "Lindsey Kurkiewicz. Fence",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-ceilings.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Ceilings (Astray)",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-altar.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Altar",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-silverware.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Silverware",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-carpets.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Ornate carpets",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-lantern.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Lantern",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-foyer-door.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Foyer entrance door",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-dungeon-door.webp",
        width: 2560,
        height: 1978,
        caption: "Leticia Trujillo. Dungeon entrance door",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/leticia-trujillo-chandelier.webp",
        width: 2560,
        height: 1978,
        caption: "Lila Chiu & Leticia Trujillo. Chandelier",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/trey-grabinger-tool-cart.webp",
        width: 1920,
        height: 1080,
        caption: "Trey Grabinger. Tool cart",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/trey-grabinger-cargo-lod.webp",
        width: 1920,
        height: 1080,
        caption: "Trey Grabinger. Cargo container, lower LOD",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/trey-grabinger-cargo.webp",
        width: 1920,
        height: 1080,
        caption: "Trey Grabinger. Cargo container",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/adam-seil-arch.webp",
        width: 1280,
        height: 720,
        caption: "Adam Seil. Arch",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/mario-ramirez-well.webp",
        width: 792,
        height: 576,
        caption: "Mario Ramirez. Well",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/adam-seil-pillar.webp",
        width: 1300,
        height: 1000,
        caption: "Adam Seil. Architectural pillar",
      },
      {
        type: "image",
        src: "/images/student-work/props-environment/bonsai.webp",
        width: 1266,
        height: 883,
        caption: "Bonsai",
      },
    ],
  },
  {
    slug: "old-master",
    title: "Old Master",
    course: "Digital Sculpting",
    description: "",
    software: [],
    cover: "/images/student-work/old-master/cover.webp",
    coverAspect: 1.7778,
    assets: [
      {
        type: "image",
        src: "/images/student-work/old-master/chris-ozouf.webp",
        width: 1280,
        height: 720,
        caption: "Chris Ozouf",
      },
      {
        type: "image",
        src: "/images/student-work/old-master/jesse-walsh.webp",
        width: 640,
        height: 480,
        caption: "Jesse Walsh",
      },
      {
        type: "image",
        src: "/images/student-work/old-master/still-life.webp",
        width: 1828,
        height: 1518,
        caption: "Still life",
      },
    ],
  },
  {
    slug: "beauty-level",
    title: "Beauty Level",
    course: "Environment / Level Design",
    description: "",
    software: [],
    cover: "/images/student-work/beauty-level/cover.webp",
    coverAspect: 1.7458,
    assets: [
      {
        type: "image",
        src: "/images/student-work/beauty-level/screen-01.webp",
        width: 1889,
        height: 1082,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screen-02.webp",
        width: 1890,
        height: 1099,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screen-03.webp",
        width: 1892,
        height: 1085,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screen-04.webp",
        width: 1894,
        height: 1094,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screen-05.webp",
        width: 1892,
        height: 1090,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screen-06.webp",
        width: 1889,
        height: 1090,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/cap-02.webp",
        width: 1847,
        height: 926,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/cap-03.webp",
        width: 1843,
        height: 921,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/pp2ss.webp",
        width: 1602,
        height: 889,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/pp4ss.webp",
        width: 1602,
        height: 889,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/ss5.webp",
        width: 1605,
        height: 893,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screenshot-01.webp",
        width: 1909,
        height: 1117,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screenshot-02.webp",
        width: 1909,
        height: 1117,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screenshot-04.webp",
        width: 1909,
        height: 1117,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screenshot-05.webp",
        width: 1844,
        height: 1039,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screenshot3.webp",
        width: 900,
        height: 600,
      },
      {
        type: "image",
        src: "/images/student-work/beauty-level/screenshot4.webp",
        width: 900,
        height: 600,
      },
    ],
  },
  {
    slug: "environments",
    title: "Environments",
    course: "Environment / Level Design",
    description: "",
    software: [],
    cover: "/images/student-work/environments/cover.webp",
    coverAspect: 1.7778,
    assets: [
      {
        type: "image",
        src: "/images/student-work/environments/cemetery.webp",
        width: 2560,
        height: 1440,
      },
      {
        type: "image",
        src: "/images/student-work/environments/mine.webp",
        width: 2442,
        height: 1374,
      },
      {
        type: "image",
        src: "/images/student-work/environments/mushroom-town.webp",
        width: 2560,
        height: 1625,
      },
      {
        type: "image",
        src: "/images/student-work/environments/warehouse.webp",
        width: 2504,
        height: 1335,
      },
      {
        type: "image",
        src: "/images/student-work/environments/office.webp",
        width: 1920,
        height: 942,
      },
      {
        type: "image",
        src: "/images/student-work/environments/vertex-interior.webp",
        width: 1920,
        height: 1040,
      },
      {
        type: "image",
        src: "/images/student-work/environments/dungeon-01.webp",
        width: 2560,
        height: 1348,
      },
      {
        type: "image",
        src: "/images/student-work/environments/dungeon-02.webp",
        width: 2560,
        height: 1342,
      },
      {
        type: "video",
        src: "/videos/student-work/adam-seil-cinematic.mp4",
        poster: "/images/student-work/environments/adam-seil-01.webp",
        width: 1272,
        height: 720,
        caption: "Adam Seil. Cinematic",
      },
      {
        type: "image",
        src: "/images/student-work/environments/adam-seil-01.webp",
        width: 2048,
        height: 2048,
        caption: "Adam Seil",
      },
      {
        type: "image",
        src: "/images/student-work/environments/adam-seil-03.webp",
        width: 2048,
        height: 2048,
        caption: "Adam Seil",
      },
      {
        type: "image",
        src: "/images/student-work/environments/adam-seil-04.webp",
        width: 2048,
        height: 2048,
        caption: "Adam Seil",
      },
      {
        type: "image",
        src: "/images/student-work/environments/adam-seil-06.webp",
        width: 2048,
        height: 2048,
        caption: "Adam Seil",
      },
      {
        type: "image",
        src: "/images/student-work/environments/lauren-smith-01.webp",
        width: 1500,
        height: 674,
        caption: "Lauren Smith",
      },
      {
        type: "image",
        src: "/images/student-work/environments/lauren-smith-02.webp",
        width: 1500,
        height: 602,
        caption: "Lauren Smith",
      },
      {
        type: "image",
        src: "/images/student-work/environments/lauren-smith-03.webp",
        width: 1500,
        height: 836,
        caption: "Lauren Smith",
      },
      {
        type: "image",
        src: "/images/student-work/environments/lauren-smith-04.webp",
        width: 1500,
        height: 836,
        caption: "Lauren Smith",
      },
    ],
  },
  {
    slug: "blueprints-behavior-trees",
    title: "Blueprints and Behavior Trees",
    description: "",
    software: [],
    cover: "/images/student-work/blueprints/cover.webp",
    coverAspect: 1.7778,
    assets: [
      {
        type: "image",
        src: "/images/student-work/blueprints/behavior-tree-01.webp",
        width: 1496,
        height: 646,
        caption: "Behavior Tree",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/behavior-tree-02.webp",
        width: 1256,
        height: 664,
        caption: "Behavior Tree",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/detection.webp",
        width: 1430,
        height: 558,
        caption: "Detection",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/detection-counter.webp",
        width: 1363,
        height: 438,
        caption: "Detection counter",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/camera-switch.webp",
        width: 1525,
        height: 606,
        caption: "Camera switch",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/enable-ray.webp",
        width: 1439,
        height: 504,
        caption: "Enable ray",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/event-graph-01.webp",
        width: 1513,
        height: 708,
        caption: "Event graph",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/event-graph-02.webp",
        width: 1140,
        height: 858,
        caption: "Event graph",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/project-blueprint.webp",
        width: 1920,
        height: 1080,
        caption: "Project blueprint",
      },
      {
        type: "image",
        src: "/images/student-work/blueprints/tool-blueprint.webp",
        width: 1920,
        height: 1080,
        caption: "Tool blueprint",
      },
    ],
  },
  {
    slug: "sigmus-omega-3",
    title: "Sigmus Omega 3",
    description: "",
    software: [],
    cover: "/images/student-work/sigmus-omega-3/cover.webp",
    coverAspect: 1.7778,
    assets: [
      {
        type: "video",
        src: "/videos/student-work/sigmus-omega-3.mp4",
        poster: "/images/student-work/sigmus-omega-3/cover.webp",
        width: 1920,
        height: 1080,
        caption: "Trailer",
      },
      {
        type: "image",
        src: "/images/student-work/sigmus-omega-3/desert-01.webp",
        width: 1936,
        height: 1056,
      },
      {
        type: "image",
        src: "/images/student-work/sigmus-omega-3/desert-02.webp",
        width: 1936,
        height: 1056,
      },
    ],
  },
  {
    slug: "rusthead-redemption",
    title: "Rusthead Redemption",
    student: "Ghost Hat Studio",
    description: "",
    software: [],
    cover: "/images/student-work/rusthead-redemption/cover.webp",
    coverAspect: 2.3333,
    assets: [
      {
        type: "video",
        src: "/videos/student-work/rusthead-redemption.mp4",
        poster: "/images/student-work/rusthead-redemption/cover.webp",
        width: 2520,
        height: 1080,
        caption: "Trailer",
      },
      {
        type: "image",
        src: "/images/student-work/rusthead-redemption/town.webp",
        width: 2560,
        height: 1440,
      },
    ],
  },
  {
    slug: "alex-vanderaa",
    title: "Alex VanDerAa",
    description: "",
    software: [],
    cover: "/images/student-work/alex-vanderaa/cover.webp",
    coverAspect: 1.5,
    assets: [
      {
        type: "video",
        src: "/videos/student-work/alex-vanderaa.mp4",
        poster: "/images/student-work/alex-vanderaa/cover.webp",
        width: 720,
        height: 480,
        caption: "Cinematic",
      },
    ],
  },
  {
    slug: "queens",
    title: "Queens",
    student: "Team Queens",
    description: "",
    software: [],
    cover: "/images/student-work/queens/cover.webp",
    coverAspect: 1.5,
    assets: [
      {
        type: "video",
        src: "/videos/student-work/queens-trailer.mp4",
        poster: "/images/student-work/queens/cover.webp",
        width: 1920,
        height: 1080,
        caption: "Trailer",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-01.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 1",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-02.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 2",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-03.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 3",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-04.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 4",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-05.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 5",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-06.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 6",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-07.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 7",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-08.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 8",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-09.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 9",
      },
      {
        type: "image",
        src: "/images/student-work/queens/screen-10.webp",
        width: 1500,
        height: 1000,
        caption: "Gameplay 10",
      },
      {
        type: "video",
        src: "/videos/student-work/queens-ant-run.mp4",
        poster: "/images/student-work/queens/cover.webp",
        width: 960,
        height: 540,
        caption: "Ant run",
      },
      {
        type: "image",
        src: "/images/student-work/queens/sheet-hon-pan-loi.webp",
        width: 1024,
        height: 720,
        caption: "Hon Pan Loi presentation sheet",
      },
      {
        type: "image",
        src: "/images/student-work/queens/sheet-julian-rojas.webp",
        width: 1224,
        height: 1584,
        caption: "Julian Rojas asset sheet",
      },
      {
        type: "image",
        src: "/images/student-work/queens/sheet-mario-ramirez.webp",
        width: 1978,
        height: 2560,
        caption: "Mario Ramirez. Antonio, the Lone Ant",
      },
      {
        type: "image",
        src: "/images/student-work/queens/sheet-michelle-segarra.webp",
        width: 1978,
        height: 2560,
        caption: "Michelle Segarra. Queen Spider",
      },
      {
        type: "image",
        src: "/images/student-work/queens/sheet-toilet-paper.webp",
        width: 612,
        height: 792,
        caption: "Toilet paper presentation sheet",
      },
    ],
  },
  {
    slug: "anatomy",
    title: "Anatomy",
    course: "Digital Sculpting",
    description: "",
    software: [],
    cover: "/images/student-work/anatomy/cover.webp",
    coverAspect: 1.5455,
    assets: [
      {
        type: "image",
        src: "/images/student-work/anatomy/hand.webp",
        width: 1080,
        height: 576,
        caption: "Hand",
      },
      {
        type: "image",
        src: "/images/student-work/anatomy/hand-wb.webp",
        width: 1224,
        height: 792,
        caption: "Hand",
      },
      {
        type: "image",
        src: "/images/student-work/anatomy/foot.webp",
        width: 1224,
        height: 792,
        caption: "Foot",
      },
    ],
  },
];
